using FishMMO.Database;
using Microsoft.Data.SqlClient;

namespace FishMMO.Installer
{
	/// <summary>
	/// Handles SqlServer provisioning and FishMMO database setup.
	/// </summary>
	public static class SqlServerInstaller
	{
		private static string BuildMasterConnectionString(SqlServerSettings settings)
		{
			var builder = new SqlConnectionStringBuilder
			{
				DataSource = settings.Server,
				InitialCatalog = "master",
				UserID = settings.Username,
				Password = settings.Password,
				TrustServerCertificate = settings.TrustServerCertificate,
				Encrypt = true
			};

			return builder.ConnectionString;
		}

		public static async Task InstallSqlServer(AppSettings appSettings)
		{
			InstallerProcessHelper.Log("SqlServer installation is environment-specific and not yet fully automated.");
			InstallerProcessHelper.Log("Ensure SqlServer is installed and reachable, then continue with FishMMO DB setup.");
			await ValidateConnection(appSettings.SqlServer);
		}

		public static Task InstallFishMMODatabase(AppSettings appSettings)
		{
			string dbName = EscapeBracketIdentifier(appSettings.SqlServer.Database);
			string sqlScript = BuildProvisioningScript(dbName);
			string fileName = $"fishmmo_sqlserver_provision_{DateTime.UtcNow:yyyyMMdd_HHmmss}.sql";
			string outputPath = Path.Combine(Directory.GetCurrentDirectory(), fileName);

			File.WriteAllText(outputPath, sqlScript);
			InstallerProcessHelper.Log($"Wrote SQL provisioning script to '{outputPath}'.");
			InstallerProcessHelper.Log("Run this script manually in SQL Server Management Studio or sqlcmd using an account with database creation permissions.");
			return Task.CompletedTask;
		}

		private static string EscapeBracketIdentifier(string identifier)
		{
			return identifier.Replace("]", "]]", StringComparison.Ordinal);
		}

		private static string BuildProvisioningScript(string escapedDatabaseName)
		{
			return $"""
-- FishMMO SQL Server provisioning script
-- Generated by FishMMO-Installer on {DateTime.UtcNow:O} (UTC)
-- NOTE: Run this script manually with an account that can create/alter databases.

USE [master];
GO

IF DB_ID(N'{escapedDatabaseName}') IS NULL
BEGIN
    CREATE DATABASE [{escapedDatabaseName}];
END
GO

ALTER DATABASE [{escapedDatabaseName}] SET COMPATIBILITY_LEVEL = 160;
GO

-- Optional: switch to the FishMMO database.
USE [{escapedDatabaseName}];
GO

-- Optional: apply EF migrations after database creation.
-- dotnet ef database update --project FishMMO-Database/FishMMO-DB/FishMMO-DB.csproj --startup-project FishMMO-Database/FishMMO-DB/FishMMO-DB.csproj
""";
		}

		private static async Task ValidateConnection(SqlServerSettings settings)
		{
			try
			{
				using var connection = new SqlConnection(BuildMasterConnectionString(settings));
				await connection.OpenAsync();
				InstallerProcessHelper.Log("SqlServer connectivity check passed.");
			}
			catch (Exception ex)
			{
				InstallerProcessHelper.Log($"Unable to connect to SqlServer: {ex.Message}");
				throw;
			}
		}
	}
}
