version: '3.8'
services:
  postgres:
    container_name: ${POSTGRES_DB}
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST}:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgresql-data:/var/lib/postgresql/data/

  redis:
    container_name: redis-container
    image: redis
    restart: always
    ports:
      - "${REDIS_HOST_STRING}:6379"
    volumes:
      - redis-data:/var/lib/redis/data/

volumes:
  postgresql-data:
  redis-data: