version: '3.8'
services:
  postgres:
    container_name: ${POSTGRES_DB}
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST}:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: