<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FishMMO.Database</RootNamespace>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8618;CS8625</NoWarn>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
        <PackageReference Include="StackExchange.Redis" Version="2.11.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>
  <!-- Define a custom property based on the existence of the marker file -->
  <PropertyGroup>
    <IsEFBuild>false</IsEFBuild>
  </PropertyGroup>
  <PropertyGroup>
    <IsEFBuild Condition="Exists('..\..\Installer.exe')">true</IsEFBuild>
  </PropertyGroup>
  <!-- Move the DLL to the Unity project. -->
  <Target Name="FishMMODependencies" AfterTargets="Build" Condition="'$(IsEFBuild)' == 'false'">
    <PropertyGroup>
      <TargetDir>..\..\FishMMO-Unity\Assets\Dependencies</TargetDir>
      <BuildConfiguration>Debug</BuildConfiguration>
    </PropertyGroup>
    <!-- Conditionally set the property based on the build configuration -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <BuildConfiguration>Release</BuildConfiguration>
    </PropertyGroup>
    <ItemGroup>
      <SourceDirWithExclusion Include="bin\$(BuildConfiguration)\**\FishMMO-DB.dll">
        <Exclude>bin\$(BuildConfiguration)\**\appsettings.json</Exclude>
      </SourceDirWithExclusion>
    </ItemGroup>
    <Copy SourceFiles="@(SourceDirWithExclusion)" DestinationFolder="$(TargetDir)" />
  </Target>
</Project>
